export const SITE_TITLE = 'Jake Korvemaa';
export const SITE_DESCRIPTION = 'Jakes personal website';

export const THEME_HUE_KEY = 'terminal-hue';

export const SOCIALS = [
    {
        title: "Email",
        icon: "envelope-fill",
        url: "mailto:contact@korvemaa.dev",
    },
    { title: "GitHub", icon: "github", url: "https://github.com/korvemaa" },
    {
        title: "LinkedIn",
        icon: "linkedin",
        url: "https://linkedin.com/in/jakekve",
    },
];

export const SKILLS = [
    "c#",
    "c/c++",
    "unity",
    "javascript",
    "azure",
    "html/css",
    "blender",
    "lua",
    "webgl",
    "substance-painter",
    "python",
    "git",
    "kubernetes",
    "figma",
].sort()

export const FLOATING_KEYWORDS = [
    "software-engineer",
    "game-developer",
    "programmer",
    "builder",
    "systems-thinker",
    "problem-solver",
    "technical",
    "creative",
    "curious",
    "independent",
    "maker",
    "tinkerer",
    "engineer",
    "developer",
    "game-dev",
    "gameplay",
    "multiplayer",
    "FPS",
    "stealth",
    "graphics",
    "rendering",
    "WebGL",
    "Unity",
    "Godot",
    "cplusplus",
    "csharp",
    "Python",
    "JavaScript",
    "GDScript",
    "Blender",
    "Azure",
    "Kubernetes",
    "Docker",
    "Linux",
    "Neovim",
    "clang",
    "automation",
    "tooling",
    "infrastructure",
    "distributed-systems",
    "cloud",
    "backend",
    "networking",
    "performance",
    "optimization",
    "engine-development",
    "native-code",
    "graphics-programming",
    "content-pipelines",
    "developer-experience",
    "system-design",
    "architecture",
    "modular",
    "maintainable",
    "experimental",
    "technical-art",
    "3D",
    "GPU",
    "hardware",
    "electronics",
    "automotive",
    "motorsports",
    "motorcycles",
    "driving",
    "coffee",
    "photography",
    "cooking",
    "music",
    "design",
    "visual-design",
    "exploration",
    "retro",
    "terminal",
    "ASCII",
    "CRT",
    "Unix",
    "maps",
    "indie",
    "self-directed",
    "ownership",
    "experimentation",
    "curiosity",
    "craft",
    "detail-oriented",
    "hands-on",
    "technical-creative",
    "espionage",
    "game-tools",
    "software-projects",
    "open-ended",
    "systems",
    "worldbuilding",
    "sci-fi",
    "retro-future",
    "modding",
    "Ravenfield",
    "WebGL",
    "Vulkan",
    "asset-pipelines",
    "file-formats",
    "editor-tools",
    "automation",
    "infrastructure",
    "maker",
    "builder",
    "c#",
    "c/c++",
    "unity",
    "javascript",
    "azure",
    "html/css",
    "blender",
    "lua",
    "webgl",
    "substance-painter",
    "python",
    "git",
    "kubernetes",
    "figma",
]